# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Ralph - AI agent loop runner"
  homepage "https://github.com/agentic-metallurgy/ralph"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.2/ralph_0.1.2_darwin_amd64.tar.gz"
      sha256 "c967d7d69c5c0c6008d9870f3d17c5ce42df953ddbd46d02df75b0af88f6f471"

      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.2/ralph_0.1.2_darwin_arm64.tar.gz"
      sha256 "1cd6658c5e997f218ff674b45b9fc2f310edf5a6981058213e2acff1cb74e437"

      def install
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.2/ralph_0.1.2_linux_amd64.tar.gz"
      sha256 "b6cba41b7fe4d5650351d67bc952bacda2c152e01dfa9dd1f87762f998ad7fa5"
      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.2/ralph_0.1.2_linux_arm64.tar.gz"
      sha256 "4478e3dbdb1eb3441431fe172dedc68e2dee1c0569f142a553062f28bb147be6"
      def install
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--help"
  end
end
