# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Ralph - AI agent loop runner"
  homepage "https://github.com/agentic-metallurgy/ralph"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.0/ralph_0.1.0_darwin_amd64.tar.gz"
      sha256 "065e0c6dd98e523bf83f1d42396ef9def0c802cca23c12d2afead74b8c8b3fec"

      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.0/ralph_0.1.0_darwin_arm64.tar.gz"
      sha256 "76fff6c008d3f158af99a0c8deff6d0c16045313698327e6dc42d975368de177"

      def install
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.0/ralph_0.1.0_linux_amd64.tar.gz"
      sha256 "901610865dd550a16c633f7c4e3b96666ae25448619205f27651de543878b820"
      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.0/ralph_0.1.0_linux_arm64.tar.gz"
      sha256 "434df3d9cbb4bb58b212c0df1e8ba9dd2ab65aa1c170f034f3e37d46be919ff2"
      def install
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--help"
  end
end
