# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Ralph - AI agent loop runner"
  homepage "https://github.com/agentic-metallurgy/ralph"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.1/ralph_0.1.1_darwin_amd64.tar.gz"
      sha256 "7d19f1c232d106bbb4d1bbdbca18f00621046845015d817e597add344d742f40"

      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.1/ralph_0.1.1_darwin_arm64.tar.gz"
      sha256 "af570299a58468a876cd065d6e948853e5aa843c7bbbc55da1fcc06f886db0ef"

      def install
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.1/ralph_0.1.1_linux_amd64.tar.gz"
      sha256 "dfbbdc9ca5a894de3340a0cbfe0bc697cfa9503f43d0d60d4f219bd57a49fa6c"
      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v0.1.1/ralph_0.1.1_linux_arm64.tar.gz"
      sha256 "20f8c20c19d78260060a85a1021d8f2b419b97e04963d96023b5a5f06f2bf240"
      def install
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--help"
  end
end
